
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Menu_de_Libros_Mayores
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Alignment alignment18;

		private global::Gtk.Alignment alignment17;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Alignment alignment16;

		private global::Gtk.Button btnAgregarLibrosMayores;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.Button btnControlLibrosMayores;

		private global::Gtk.Alignment alignment14;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Menu_de_Libros_Mayores
			this.Name = "Contabilidad_General.Menu_de_Libros_Mayores";
			this.Title = global::Mono.Unix.Catalog.GetString("Menu_de_Libros_Mayores");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Menu_de_Libros_Mayores.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment18.Name = "alignment18";
			this.hbox7.Add(this.alignment18);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.alignment18]));
			w1.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			this.hbox7.Add(this.alignment17);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.alignment17]));
			w2.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox7.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox6.Add(this.hbox7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox7]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Menu de Libros Mayores\n");
			this.vbox7.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			this.hbox8.Add(this.alignment16);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment16]));
			w6.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnAgregarLibrosMayores = new global::Gtk.Button();
			this.btnAgregarLibrosMayores.CanFocus = true;
			this.btnAgregarLibrosMayores.Name = "btnAgregarLibrosMayores";
			this.btnAgregarLibrosMayores.UseUnderline = true;
			this.btnAgregarLibrosMayores.Label = global::Mono.Unix.Catalog.GetString("Agregar Libros Mayores    ");
			this.hbox8.Add(this.btnAgregarLibrosMayores);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnAgregarLibrosMayores]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.hbox8.Add(this.alignment13);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment13]));
			w8.Position = 2;
			this.vbox7.Add(this.hbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox8]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			this.hbox9.Add(this.alignment15);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment15]));
			w10.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnControlLibrosMayores = new global::Gtk.Button();
			this.btnControlLibrosMayores.CanFocus = true;
			this.btnControlLibrosMayores.Name = "btnControlLibrosMayores";
			this.btnControlLibrosMayores.UseUnderline = true;
			this.btnControlLibrosMayores.Label = global::Mono.Unix.Catalog.GetString("Control de Libros Mayores");
			this.hbox9.Add(this.btnControlLibrosMayores);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnControlLibrosMayores]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			this.hbox9.Add(this.alignment14);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment14]));
			w12.Position = 2;
			this.vbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox6.Add(this.vbox7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox7]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 162;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
			this.btnAgregarLibrosMayores.Clicked += new global::System.EventHandler(this.OnBtnAgregarLibrosMayoresClicked);
			this.btnControlLibrosMayores.Clicked += new global::System.EventHandler(this.OnBtnControlLibrosMayoresClicked);
		}
	}
}
