
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Menu_de_Libros_diarios
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.Button btnAgregarLibrosDiarios;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.Button btnControlLibrosDiarios;

		private global::Gtk.Alignment alignment10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Menu_de_Libros_diarios
			this.Name = "Contabilidad_General.Menu_de_Libros_diarios";
			this.Title = global::Mono.Unix.Catalog.GetString("Menu_de_Libros_diarios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Menu_de_Libros_diarios.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox4.Add(this.alignment8);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment8]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox4.Add(this.alignment7);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment7]));
			w2.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox4.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add(this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Menu de Libros Diarios\n");
			this.vbox5.Add(this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.hbox5.Add(this.alignment11);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.alignment11]));
			w6.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnAgregarLibrosDiarios = new global::Gtk.Button();
			this.btnAgregarLibrosDiarios.CanFocus = true;
			this.btnAgregarLibrosDiarios.Name = "btnAgregarLibrosDiarios";
			this.btnAgregarLibrosDiarios.UseUnderline = true;
			this.btnAgregarLibrosDiarios.Label = global::Mono.Unix.Catalog.GetString("Agregar Libros Diarios    ");
			this.hbox5.Add(this.btnAgregarLibrosDiarios);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnAgregarLibrosDiarios]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox5.Add(this.alignment9);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.alignment9]));
			w8.Position = 2;
			this.vbox5.Add(this.hbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.hbox6.Add(this.alignment12);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.alignment12]));
			w10.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnControlLibrosDiarios = new global::Gtk.Button();
			this.btnControlLibrosDiarios.CanFocus = true;
			this.btnControlLibrosDiarios.Name = "btnControlLibrosDiarios";
			this.btnControlLibrosDiarios.UseUnderline = true;
			this.btnControlLibrosDiarios.Label = global::Mono.Unix.Catalog.GetString("Control de Libros Diarios");
			this.hbox6.Add(this.btnControlLibrosDiarios);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnControlLibrosDiarios]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.hbox6.Add(this.alignment10);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.alignment10]));
			w12.Position = 2;
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox4.Add(this.vbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 153;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
			this.btnAgregarLibrosDiarios.Clicked += new global::System.EventHandler(this.OnBtnAgregarLibrosDiariosClicked);
			this.btnControlLibrosDiarios.Clicked += new global::System.EventHandler(this.OnBtnControlLibrosDiariosClicked);
		}
	}
}
