
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Agregar_Libro_mayor
	{
		private global::Gtk.VBox vbox27;

		private global::Gtk.HBox hbox48;

		private global::Gtk.Alignment alignment27;

		private global::Gtk.Alignment alignment26;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox28;

		private global::Gtk.Label label44;

		private global::Gtk.HBox hbox52;

		private global::Gtk.Label label48;

		private global::Gtk.ComboBox cmbMes;

		private global::Gtk.Label label49;

		private global::Gtk.ComboBox cmbIDPeriodo;

		private global::Gtk.VBox vbox29;

		private global::Gtk.HBox hbox53;

		private global::Gtk.Label label51;

		private global::Gtk.ComboBox cmbIDUsuario;

		private global::Gtk.Label label52;

		private global::Gtk.ComboBox cmbEmpresa;

		private global::Gtk.Label label53;

		private global::Gtk.ComboBox cmbActivo;

		private global::Gtk.HBox hbox54;

		private global::Gtk.Label label54;

		private global::Gtk.Entry txtConcepto;

		private global::Gtk.HBox hbox55;

		private global::Gtk.VBox vbox32;

		private global::Gtk.Label label59;

		private global::Gtk.ScrolledWindow scrolledwindow7;

		private global::Gtk.TreeView tvLibroMayor;

		private global::Gtk.VBox vbox33;

		private global::Gtk.Label label60;

		private global::Gtk.HBox hbox61;

		private global::Gtk.Label label61;

		private global::Gtk.Entry txtFecha;

		private global::Gtk.Button btnDefinir;

		private global::Gtk.ScrolledWindow scrolledwindow8;

		private global::Gtk.TreeView tvLibroDiario;

		private global::Gtk.VBox vbox30;

		private global::Gtk.HBox hbox57;

		private global::Gtk.Label label55;

		private global::Gtk.Entry txtTotalDebe;

		private global::Gtk.HBox hbox58;

		private global::Gtk.Label label56;

		private global::Gtk.Entry txtTotalHaber;

		private global::Gtk.VBox vbox31;

		private global::Gtk.HBox hbox59;

		private global::Gtk.Label label57;

		private global::Gtk.Entry txtIDAsiento;

		private global::Gtk.HBox hbox60;

		private global::Gtk.Label label58;

		private global::Gtk.Entry txtIDCatalogoCuenta;

		private global::Gtk.HBox hbox56;

		private global::Gtk.Button btnNuevoElemento;

		private global::Gtk.Button btnGuardar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Agregar_Libro_mayor
			this.Name = "Contabilidad_General.Agregar_Libro_mayor";
			this.Title = global::Mono.Unix.Catalog.GetString("Agregar_Libro_mayor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Agregar_Libro_mayor.Gtk.Container+ContainerChild
			this.vbox27 = new global::Gtk.VBox();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.hbox48 = new global::Gtk.HBox();
			this.hbox48.Name = "hbox48";
			this.hbox48.Spacing = 6;
			// Container child hbox48.Gtk.Box+BoxChild
			this.alignment27 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment27.Name = "alignment27";
			this.hbox48.Add(this.alignment27);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.alignment27]));
			w1.Position = 0;
			// Container child hbox48.Gtk.Box+BoxChild
			this.alignment26 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment26.Name = "alignment26";
			this.hbox48.Add(this.alignment26);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.alignment26]));
			w2.Position = 1;
			// Container child hbox48.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox48.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox27.Add(this.hbox48);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.hbox48]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.label44 = new global::Gtk.Label();
			this.label44.Name = "label44";
			this.label44.LabelProp = global::Mono.Unix.Catalog.GetString("Libro Mayor");
			this.vbox28.Add(this.label44);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label44]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox52 = new global::Gtk.HBox();
			this.hbox52.Name = "hbox52";
			this.hbox52.Spacing = 6;
			// Container child hbox52.Gtk.Box+BoxChild
			this.label48 = new global::Gtk.Label();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString("Mes:");
			this.hbox52.Add(this.label48);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.label48]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox52.Gtk.Box+BoxChild
			this.cmbMes = global::Gtk.ComboBox.NewText();
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Enero"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Febrero"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Marzo"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Abril"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Mayo"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Junio"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Julio"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Agosto"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Septiembre"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Octubre"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Noviembre"));
			this.cmbMes.AppendText(global::Mono.Unix.Catalog.GetString("Diciembre"));
			this.cmbMes.Name = "cmbMes";
			this.hbox52.Add(this.cmbMes);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.cmbMes]));
			w7.Position = 1;
			// Container child hbox52.Gtk.Box+BoxChild
			this.label49 = new global::Gtk.Label();
			this.label49.Name = "label49";
			this.label49.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Periodo Contable:");
			this.hbox52.Add(this.label49);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.label49]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox52.Gtk.Box+BoxChild
			this.cmbIDPeriodo = global::Gtk.ComboBox.NewText();
			this.cmbIDPeriodo.Name = "cmbIDPeriodo";
			this.hbox52.Add(this.cmbIDPeriodo);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.cmbIDPeriodo]));
			w9.Position = 3;
			this.vbox28.Add(this.hbox52);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox52]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.vbox29 = new global::Gtk.VBox();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			this.vbox29.BorderWidth = ((uint)(3));
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox53 = new global::Gtk.HBox();
			this.hbox53.Name = "hbox53";
			this.hbox53.Spacing = 6;
			// Container child hbox53.Gtk.Box+BoxChild
			this.label51 = new global::Gtk.Label();
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.hbox53.Add(this.label51);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.label51]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.cmbIDUsuario = global::Gtk.ComboBox.NewText();
			this.cmbIDUsuario.Name = "cmbIDUsuario";
			this.hbox53.Add(this.cmbIDUsuario);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.cmbIDUsuario]));
			w12.Position = 1;
			// Container child hbox53.Gtk.Box+BoxChild
			this.label52 = new global::Gtk.Label();
			this.label52.Name = "label52";
			this.label52.LabelProp = global::Mono.Unix.Catalog.GetString("Empresa:");
			this.hbox53.Add(this.label52);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.label52]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.cmbEmpresa = global::Gtk.ComboBox.NewText();
			this.cmbEmpresa.Name = "cmbEmpresa";
			this.hbox53.Add(this.cmbEmpresa);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.cmbEmpresa]));
			w14.Position = 3;
			// Container child hbox53.Gtk.Box+BoxChild
			this.label53 = new global::Gtk.Label();
			this.label53.Name = "label53";
			this.label53.LabelProp = global::Mono.Unix.Catalog.GetString("Estado del Libro:");
			this.hbox53.Add(this.label53);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.label53]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.cmbActivo = global::Gtk.ComboBox.NewText();
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActivo.Name = "cmbActivo";
			this.hbox53.Add(this.cmbActivo);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.cmbActivo]));
			w16.Position = 5;
			this.vbox29.Add(this.hbox53);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox53]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox54 = new global::Gtk.HBox();
			this.hbox54.Name = "hbox54";
			this.hbox54.Spacing = 6;
			// Container child hbox54.Gtk.Box+BoxChild
			this.label54 = new global::Gtk.Label();
			this.label54.Name = "label54";
			this.label54.LabelProp = global::Mono.Unix.Catalog.GetString("Concepto del Movimiento:");
			this.hbox54.Add(this.label54);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox54[this.label54]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox54.Gtk.Box+BoxChild
			this.txtConcepto = new global::Gtk.Entry();
			this.txtConcepto.CanFocus = true;
			this.txtConcepto.Name = "txtConcepto";
			this.txtConcepto.IsEditable = true;
			this.txtConcepto.InvisibleChar = '•';
			this.hbox54.Add(this.txtConcepto);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox54[this.txtConcepto]));
			w19.Position = 1;
			this.vbox29.Add(this.hbox54);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox54]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox55 = new global::Gtk.HBox();
			this.hbox55.Name = "hbox55";
			this.hbox55.Spacing = 6;
			// Container child hbox55.Gtk.Box+BoxChild
			this.vbox32 = new global::Gtk.VBox();
			this.vbox32.Name = "vbox32";
			this.vbox32.Spacing = 6;
			// Container child vbox32.Gtk.Box+BoxChild
			this.label59 = new global::Gtk.Label();
			this.label59.Name = "label59";
			this.label59.LabelProp = global::Mono.Unix.Catalog.GetString("                                Detalles del Libro Mayor                         " +
					"                     ");
			this.vbox32.Add(this.label59);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.label59]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.scrolledwindow7 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow7.CanFocus = true;
			this.scrolledwindow7.Name = "scrolledwindow7";
			this.scrolledwindow7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow7.Gtk.Container+ContainerChild
			this.tvLibroMayor = new global::Gtk.TreeView();
			this.tvLibroMayor.CanFocus = true;
			this.tvLibroMayor.Name = "tvLibroMayor";
			this.scrolledwindow7.Add(this.tvLibroMayor);
			this.vbox32.Add(this.scrolledwindow7);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.scrolledwindow7]));
			w23.Position = 1;
			// Container child vbox32.Gtk.Box+BoxChild
			this.vbox33 = new global::Gtk.VBox();
			this.vbox33.Name = "vbox33";
			this.vbox33.Spacing = 6;
			// Container child vbox33.Gtk.Box+BoxChild
			this.label60 = new global::Gtk.Label();
			this.label60.Name = "label60";
			this.label60.LabelProp = global::Mono.Unix.Catalog.GetString("Detalles del Libro Diario");
			this.vbox33.Add(this.label60);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox33[this.label60]));
			w24.Position = 0;
			// Container child vbox33.Gtk.Box+BoxChild
			this.hbox61 = new global::Gtk.HBox();
			this.hbox61.Name = "hbox61";
			this.hbox61.Spacing = 6;
			// Container child hbox61.Gtk.Box+BoxChild
			this.label61 = new global::Gtk.Label();
			this.label61.Name = "label61";
			this.label61.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha:");
			this.hbox61.Add(this.label61);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox61[this.label61]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox61.Gtk.Box+BoxChild
			this.txtFecha = new global::Gtk.Entry();
			this.txtFecha.CanFocus = true;
			this.txtFecha.Name = "txtFecha";
			this.txtFecha.IsEditable = true;
			this.txtFecha.InvisibleChar = '•';
			this.hbox61.Add(this.txtFecha);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox61[this.txtFecha]));
			w26.Position = 1;
			// Container child hbox61.Gtk.Box+BoxChild
			this.btnDefinir = new global::Gtk.Button();
			this.btnDefinir.CanFocus = true;
			this.btnDefinir.Name = "btnDefinir";
			this.btnDefinir.UseUnderline = true;
			this.btnDefinir.Label = global::Mono.Unix.Catalog.GetString("Definir");
			this.hbox61.Add(this.btnDefinir);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox61[this.btnDefinir]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox33.Add(this.hbox61);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox33[this.hbox61]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox33.Gtk.Box+BoxChild
			this.scrolledwindow8 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow8.CanFocus = true;
			this.scrolledwindow8.Name = "scrolledwindow8";
			this.scrolledwindow8.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow8.Gtk.Container+ContainerChild
			this.tvLibroDiario = new global::Gtk.TreeView();
			this.tvLibroDiario.CanFocus = true;
			this.tvLibroDiario.Name = "tvLibroDiario";
			this.scrolledwindow8.Add(this.tvLibroDiario);
			this.vbox33.Add(this.scrolledwindow8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox33[this.scrolledwindow8]));
			w30.Position = 2;
			this.vbox32.Add(this.vbox33);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.vbox33]));
			w31.Position = 2;
			this.hbox55.Add(this.vbox32);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox55[this.vbox32]));
			w32.Position = 0;
			// Container child hbox55.Gtk.Box+BoxChild
			this.vbox30 = new global::Gtk.VBox();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			this.vbox30.BorderWidth = ((uint)(9));
			// Container child vbox30.Gtk.Box+BoxChild
			this.hbox57 = new global::Gtk.HBox();
			this.hbox57.Name = "hbox57";
			this.hbox57.Spacing = 6;
			// Container child hbox57.Gtk.Box+BoxChild
			this.label55 = new global::Gtk.Label();
			this.label55.Name = "label55";
			this.label55.LabelProp = global::Mono.Unix.Catalog.GetString("                                  Total debe:");
			this.hbox57.Add(this.label55);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox57[this.label55]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox57.Gtk.Box+BoxChild
			this.txtTotalDebe = new global::Gtk.Entry();
			this.txtTotalDebe.CanFocus = true;
			this.txtTotalDebe.Name = "txtTotalDebe";
			this.txtTotalDebe.IsEditable = true;
			this.txtTotalDebe.InvisibleChar = '•';
			this.hbox57.Add(this.txtTotalDebe);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox57[this.txtTotalDebe]));
			w34.Position = 1;
			this.vbox30.Add(this.hbox57);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.hbox57]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.hbox58 = new global::Gtk.HBox();
			this.hbox58.Name = "hbox58";
			this.hbox58.Spacing = 6;
			// Container child hbox58.Gtk.Box+BoxChild
			this.label56 = new global::Gtk.Label();
			this.label56.Name = "label56";
			this.label56.LabelProp = global::Mono.Unix.Catalog.GetString("                               Total Haber:");
			this.hbox58.Add(this.label56);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox58[this.label56]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox58.Gtk.Box+BoxChild
			this.txtTotalHaber = new global::Gtk.Entry();
			this.txtTotalHaber.CanFocus = true;
			this.txtTotalHaber.Name = "txtTotalHaber";
			this.txtTotalHaber.IsEditable = true;
			this.txtTotalHaber.InvisibleChar = '•';
			this.hbox58.Add(this.txtTotalHaber);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox58[this.txtTotalHaber]));
			w37.Position = 1;
			this.vbox30.Add(this.hbox58);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.hbox58]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.vbox31 = new global::Gtk.VBox();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox59 = new global::Gtk.HBox();
			this.hbox59.Name = "hbox59";
			this.hbox59.Spacing = 6;
			// Container child hbox59.Gtk.Box+BoxChild
			this.label57 = new global::Gtk.Label();
			this.label57.Name = "label57";
			this.label57.LabelProp = global::Mono.Unix.Catalog.GetString("     ID del Asiento Contable:");
			this.hbox59.Add(this.label57);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox59[this.label57]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox59.Gtk.Box+BoxChild
			this.txtIDAsiento = new global::Gtk.Entry();
			this.txtIDAsiento.CanFocus = true;
			this.txtIDAsiento.Name = "txtIDAsiento";
			this.txtIDAsiento.IsEditable = true;
			this.txtIDAsiento.InvisibleChar = '•';
			this.hbox59.Add(this.txtIDAsiento);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox59[this.txtIDAsiento]));
			w40.Position = 1;
			this.vbox31.Add(this.hbox59);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox59]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox60 = new global::Gtk.HBox();
			this.hbox60.Name = "hbox60";
			this.hbox60.Spacing = 6;
			// Container child hbox60.Gtk.Box+BoxChild
			this.label58 = new global::Gtk.Label();
			this.label58.Name = "label58";
			this.label58.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Catalogo de Cuenta:");
			this.hbox60.Add(this.label58);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox60[this.label58]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox60.Gtk.Box+BoxChild
			this.txtIDCatalogoCuenta = new global::Gtk.Entry();
			this.txtIDCatalogoCuenta.CanFocus = true;
			this.txtIDCatalogoCuenta.Name = "txtIDCatalogoCuenta";
			this.txtIDCatalogoCuenta.IsEditable = true;
			this.txtIDCatalogoCuenta.InvisibleChar = '•';
			this.hbox60.Add(this.txtIDCatalogoCuenta);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox60[this.txtIDCatalogoCuenta]));
			w43.Position = 1;
			this.vbox31.Add(this.hbox60);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox60]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox56 = new global::Gtk.HBox();
			this.hbox56.Name = "hbox56";
			this.hbox56.Spacing = 6;
			// Container child hbox56.Gtk.Box+BoxChild
			this.btnNuevoElemento = new global::Gtk.Button();
			this.btnNuevoElemento.CanFocus = true;
			this.btnNuevoElemento.Name = "btnNuevoElemento";
			this.btnNuevoElemento.UseUnderline = true;
			this.btnNuevoElemento.Label = global::Mono.Unix.Catalog.GetString("Nuevo Elemento");
			this.hbox56.Add(this.btnNuevoElemento);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox56[this.btnNuevoElemento]));
			w45.Position = 0;
			w45.Fill = false;
			// Container child hbox56.Gtk.Box+BoxChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbox56.Add(this.btnGuardar);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox56[this.btnGuardar]));
			w46.Position = 1;
			w46.Fill = false;
			this.vbox31.Add(this.hbox56);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox56]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			this.vbox30.Add(this.vbox31);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.vbox31]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox55.Add(this.vbox30);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox55[this.vbox30]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			this.vbox29.Add(this.hbox55);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox55]));
			w50.Position = 2;
			this.vbox28.Add(this.vbox29);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.vbox29]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox27.Add(this.vbox28);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.vbox28]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			this.Add(this.vbox27);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 783;
			this.DefaultHeight = 467;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
			this.btnDefinir.Clicked += new global::System.EventHandler(this.OnBtnDefinirClicked);
			this.tvLibroDiario.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTvLibroDiarioRowActivated);
			this.btnNuevoElemento.Clicked += new global::System.EventHandler(this.OnBtnNuevoElementoClicked);
		}
	}
}
